name: Node CI

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: npm install && npm test && npm run build
      env:
        CI: true
        
    - name: Build Docker image
      run: |
         echo ${BRANCH#/refs/heads/}
         echo $BRANCH
         docker build -t xebxke/totoactions:${BRANCH#/refs/heads/}/$COMMIT .
      env: 
        BRANCH: ${{ github.ref }}
        COMMIT: ${{ github.sha }}
    - name : Push Docker image to repo
      run: |
        docker login xebxke -u $DOCKER_PUSH_USERNAME -p $DOCKER_PUSH_PASSWORD
        docker push xebxke/totoactions:${BRANCH#/refs/heads/}/$COMMIT
      env:
        DOCKER_PUSH_USERNAME: ${{ secrets.DOCKER_PUSH_USERNAME }}
        DOCKER_PUSH_PASSWORD: ${{ secrets.DOCKER_PUSH_PASSWORD }}
